export const fallbackVideos = [
  {
    _id: "1",
    title: "Next.js 13 Crash Course",
    description: "Learn the basics of Next.js 13 in this comprehensive crash course. We'll cover routing, server components, data fetching, and more!",
    videoUrl: "https://www.youtube.com/embed/cBPOL5biuOs",
    thumbnailUrl: "/placeholder.svg?height=180&width=320",
    views: 120000,
    likes: 10000,
    dislikes: 100,
    channel: "Code with Anna",
    channelAvatar: "/placeholder.svg?height=48&width=48",
    subscribers: 500000,
    timestamp: new Date("2023-05-01").toISOString(),
  },
  {
    _id: "2",
    title: "React Hooks Explained",
    description: "Dive deep into React Hooks and learn how to use them effectively in your projects.",
    videoUrl: "https://www.youtube.com/embed/cBPOL5biuOs",
    thumbnailUrl: "/placeholder.svg?height=180&width=320",
    views: 250000,
    likes: 15000,
    dislikes: 200,
    channel: "JavaScript Mastery",
    channelAvatar: "/placeholder.svg?height=48&width=48",
    subscribers: 750000,
    timestamp: new Date("2023-04-15").toISOString(),
  },
  {
    _id: "3",
    title: "Building a REST API with Node.js",
    description: "Learn how to build a robust REST API using Node.js and Express.",
    videoUrl: "https://www.youtube.com/embed/cBPOL5biuOs",
    thumbnailUrl: "/placeholder.svg?height=180&width=320",
    views: 80000,
    likes: 5000,
    dislikes: 50,
    channel: "Backend Basics",
    channelAvatar: "/placeholder.svg?height=48&width=48",
    subscribers: 300000,
    timestamp: new Date("2023-04-30").toISOString(),
  },
  {
    _id: "4",
    title: "CSS Grid Layout Tutorial",
    description: "Master CSS Grid Layout with this comprehensive tutorial.",
    videoUrl: "https://www.youtube.com/embed/cBPOL5biuOs",
    thumbnailUrl: "/placeholder.svg?height=180&width=320",
    views: 150000,
    likes: 8000,
    dislikes: 100,
    channel: "CSS Wizardry",
    channelAvatar: "/placeholder.svg?height=48&width=48",
    subscribers: 400000,
    timestamp: new Date("2023-05-05").toISOString(),
  },
];

export const fallbackComments = [
  {
    _id: "1",
    videoId: "1",
    user: "John Doe",
    userAvatar: "/placeholder.svg?height=40&width=40",
    content: "Great tutorial! Really helped me understand Next.js 13.",
    timestamp: new Date("2023-05-02").toISOString(),
  },
  {
    _id: "2",
    videoId: "1",
    user: "Jane Smith",
    userAvatar: "/placeholder.svg?height=40&width=40",
    content: "Could you make a follow-up video on Server Components?",
    timestamp: new Date("2023-05-03").toISOString(),
  },
];

